name: CI

on: [push]

jobs:
  test:
    name: Build and test with os ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
       
    steps:
      - uses: actions/checkout@v1
      - name: Download node.js 10.11.0 (version used in VSCode)
        uses: actions/setup-node@v1
        with:
          node-version: 10.11.0

      - name: Install deps and compile
        run: |
          npm install --only=dev
          npm install
          npm run test-compile
          
      - name: Run tests with xvfb-run
        run: xvfb-run npm run test
        if: matrix.os == 'ubuntu-latest'
        
      - name: Run tests (no xvfb, we have a gui)
        run: npm run test
        if: matrix.os != 'ubuntu-latest'
   
  package:
    name: Package to .vsix and upload
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v1
    - name: Download node.js 10.11.0 (version used in VSCode)
      uses: actions/setup-node@v1
      with:
        version: 10.11.0
          
    - name: npm install deps
      run: |
        npm install --only=dev && npm install
        
    - name: Install vsce from my repo
      run: |
        git clone https://github.com/ItsMajestiX/vscode-vsce.git
        cd vscode-vsce
        npm install --only=dev
        npm install
        tsc
        cp src/vsce out/vsce
        cd ..
          
    - name: Create .vsix file
      run: |
        ./vscode-vsce/out/vsce package
        mkdir artifacts
        mv *.vsix artifacts/
          
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: vscode-ti
        path: artifacts
            
- name: Publish VS Code Extension
  # You may pin to the exact commit or the version.
  # uses: HaaLeo/publish-vscode-extension@50cf7921c9e1bc32992682b15b5760ba28973e85
  uses: HaaLeo/publish-vscode-extension@v0
  with:
    # Personal access token
    pat: 
    # Path to the vsix file to be published. Cannot be used together with packagePath.
    extensionFile: # optional
    # Use the registry API at this base URL
    registryUrl: # optional, default is https://open-vsx.org
    # Path to the extension to be packaged and published. Cannot be used together with extensionFile.
    packagePath: # optional, default is ./
    # Prepend all relative links in README.md with this URL.
    baseContentUrl: # optional
    # Prepend all relative image links in README.md with this URL.
    baseImagesUrl: # optional
    # Use yarn instead of npm while packing extension files.
    yarn: # optional
    # Set this option to "true" to package your extension but do not publish it.
    dryRun: # optional
        
